# -*- coding: utf-8 -*-
"""arithmetic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y61iclxoV2a36jemAtqiK-4cgsUIXcGr
"""

# math/operations.py

import math

# Basic arithmetic operations
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        raise ValueError("Division by zero is not allowed")
    return a / b

def modulus(a, b):
    return a % b

# Advanced mathematical operations
def exponentiate(base, exponent):
    return base ** exponent

def square_root(x):
    if x < 0:
        raise ValueError("Square root of a negative number is not real")
    return math.sqrt(x)