# -*- coding: utf-8 -*-
"""file handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0zhpwPG8CTYbrAfDCMpUc4sUoc4JI-6
"""

#first i have a function, which will first check if the file exists or not
def file_exists(filename):
    try:

          #if it opens succesfully, it will simply read the file. otherwise it will give error
        with open(filename, 'r'):
            pass
        return True
    except FileNotFoundError:
        return False
    except IOError:
        return False

#now to read the file, i first called the file exists function
def read_file_contents(filename):
    if file_exists(filename):
        try:

              #if the file exists, it will first open it, and store whatever is in the file in a variable
            with open(filename, 'r') as file:
                contents = file.read()

                #and then it will print
                print(f"Contents of '{filename}':\n{contents}")

            #if the file does not exists, or if thee is an error in opening it, it will print a message
        except IOError as e:
            print(f"Error reading from file '{filename}': {e}")
    else:
        print(f"Error: File '{filename}' not found or cannot be accessed.")

#now to write to my output file, i once again first called my file exists function, to see if it exists and if it will open or not
def write_to_file(filename, content):
    if file_exists(filename):
        try:

                #if it exists then it will write the user input to the file
            with open(filename, 'w') as file:
                file.write(content)
            print(f"Data written to '{filename}' successfully.")
        except IOError as e:
            print(f"Error writing to file '{filename}': {e}")
    else:
        print(f"Error: File '{filename}' not found or cannot be accessed.")


      #next to count the words, it will first read the file and split the content of the file
def count_words_in_file(filename):
    if file_exists(filename):
        try:
            with open(filename, 'r') as file:
                contents = file.read()
                words = contents.split()

                  #after splitting, i used the lenght function to get the number of words
                word_count = len(words)
                print(f"Number of words in '{filename}': {word_count}")
        except IOError as e:
            print(f"Error reading from file '{filename}': {e}")
    else:
        print(f"Error: File '{filename}' not found or cannot be accessed.")


def main():

    read_file_contents('file1.txt')


    user_input = input("Enter content to write to file: ")
    write_to_file('result.txt', user_input)

    count_words_in_file('file1.txt')

if __name__ == "__main__":
    main()