# -*- coding: utf-8 -*-
"""finalmain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZfVgSNlj98Si_o4lxgyDoQ8pSe4qYFa


import datetime
from invents1 import Inventory
from items import FoodItem

def main():
    inventory = Inventory()

    while True:
        print("\n===== Inventory Management System =====")
        print("1. Add Item")
        print("2. Edit Item")
        print("3. Delete Item")
        print("4. Search Item")
        print("5. View Near Expiry Items")
        print("6. Save Inventory to CSV")
        print("7. Exit")

        choice = input("Enter your choice (1-8): ")

        if choice == '1':
            add_item(inventory)
        elif choice == '2':
            edit_item(inventory)
        elif choice == '3':
            delete_item(inventory)
        elif choice == '4':
            search_item(inventory)
        elif choice == '5':
            view_near_expiry_items(inventory)
        elif choice == '6':
            save_inventory(inventory)
        elif choice == '7':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please enter a number from 1 to 8.")

def add_item(inventory):
    print("\nAdding a new item...")
    name = input("Enter name: ")
    category = input("Enter category: ")
    quantity = int(input("Enter quantity: "))
    barcode = input("Enter barcode: ")
    expiry_date = input("Enter expiry date (YYYY-MM-DD): ")
    expiry_date = datetime.datetime.strptime(expiry_date, '%Y-%m-%d').date()
    new_item = FoodItem(name, category, quantity, barcode, expiry_date)
    inventory.add_item(new_item)
    print("Item added successfully.")

def edit_item(inventory):
    barcode = input("\nEnter barcode of item to edit: ")
    new_quantity = int(input("Enter new quantity: "))
    inventory.edit_item(barcode, new_quantity)
    print("Item quantity updated successfully.")

def delete_item(inventory):
    barcode = input("\nEnter barcode of item to delete: ")
    inventory.delete_item(barcode)
    print("Item deleted successfully.")

def search_item(inventory):
    search_type = input("\nSearch by (1) Barcode or (2) Name: ")
    if search_type == '1':
        barcode = input("Enter barcode to search: ")
        item = inventory.search_item_by_barcode(barcode)
    elif search_type == '2':
        name = input("Enter name to search: ")
        item = inventory.search_item_by_name(name)
    else:
        print("Invalid choice.")
        return

    if item:
        print(f"\nItem found: {item.name}, Category: {item.category}, Quantity: {item.quantity}, Barcode: {item.barcode}, Expiry Date: {item.expiry_date}")
    else:
        print("Item not found.")

def view_near_expiry_items(inventory):
    today_date = datetime.date.today()
    near_expiry_items = inventory.get_near_expiry_items(today_date)
    if near_expiry_items:
        print("\nNear expiry items:")
        for item in near_expiry_items:
            print(f"{item.name}, Expiry Date: {item.expiry_date}")
    else:
        print("No items are near expiry.")

def save_inventory(inventory):
    filename = input("Enter filename to save inventory data: ")
    inventory.save_inventory_to_csv(filename)



if __name__ == "__main__":
    main()
