# -*- coding: utf-8 -*-
"""inevents1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ND7jMh9q8P1P7DTt-NKpy60IO2jrJUDN
"""

# inventory.py

import datetime
import csv
from items import FoodItem  # Import FoodItem class from fooditem.py

class Inventory:
    def __init__(self):
        self.inventory = []

    def add_item(self, food_item):
        self.inventory.append(food_item)

    def edit_item(self, barcode, new_quantity):
        for item in self.inventory:
            if item.barcode == barcode:
                item.quantity = new_quantity
                break

    def delete_item(self, barcode):
        for item in self.inventory:
            if item.barcode == barcode:
                self.inventory.remove(item)
                break

    def search_item_by_barcode(self, barcode):
        for item in self.inventory:
            if item.barcode == barcode:
                return item
        return None

    def search_item_by_name(self, name):
        for item in self.inventory:
            if item.name == name:
                return item
        return None

    def get_near_expiry_items(self, today_date, days_threshold=7):
        near_expiry_items = []
        for item in self.inventory:
            if isinstance(item.expiry_date, str):
                expiry_date = datetime.datetime.strptime(item.expiry_date, '%Y-%m-%d').date()
            else:
                expiry_date = item.expiry_date  # assuming expiry_date is already a date object

            delta = expiry_date - today_date
            if 0 <= delta.days <= days_threshold:
                near_expiry_items.append(item)

        return near_expiry_items

    def save_inventory_to_csv(self, filename):
        try:
            with open(filename, mode='w', newline='') as file:
                writer = csv.writer(file)
                writer.writerow(["Name", "Category", "Quantity", "Barcode", "Expiry Date"])
                for item in self.inventory:
                    writer.writerow([item.name, item.category, item.quantity, item.barcode, item.expiry_date.strftime('%Y-%m-%d')])
            print(f"Inventory data saved to {filename}")
        except IOError as e:
            print(f"Error saving inventory to {filename}: {e}")

