# -*- coding: utf-8 -*-
"""items.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0gOQl5kWcMpL3zynDqzbULvBbcHiPMP
"""

#now in my food class file, i have created a class in which
import csv
class FoodItem:
    def __init__(self, name, category, quantity, barcode, expiry_date):

        #i created an objects, which will have the below 5 attributes
      self.name = name
      self.category = category
      self.quantity = quantity
      self.barcode = barcode
      self.expiry_date = expiry_date