# -*- coding: utf-8 -*-
"""LMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWPIQvhmfq_oPj8Zep5SlfjWCRHDCIT8

# **Task Number 1**
"""

#first i created a class called Book
class Book:
  #then i created a kind of a constructor, which will be called when an object is created
  def __init__(self):
    #i then assigned values by passing arguments to the object. Instead of hardcoding, ive asked the user to input the information using input function
    self.title =  input("Please enter book title: ")
    self.author = input("Please enter book author: ")
    self.pages =  input("Please enter the number of pages in the book")

    #next i have my getter and setters for each attribute


  #first we have my getter functions
  def get_booktitle(self):
    return self.title

  def get_bookauthor(self):
    return self.author

  def get_bookpages(self):
    return self.pages

  #next we have my setter functions
  def set_booktitle(self , title):
   self.title = title

  def set_bookauthor(self , author):
   self.author = author

  def set_bookpages(self , pages):
   self.pages = pages


        #next i have a function which will calculate my reading time by dividing the number of words by the words per minutr
  def calculate_reading_time(num_words, words_per_minute=400):
        minutes = num_words / words_per_minute
        return minutes

book1 = Book()

print(f"Title: {book1.get_booktitle()}, Author: {book1.get_bookauthor()}, Pages: {book1.get_bookpages()}")

book1.set_booktitle("Divergent")
print(f"Updated Title: {book1.get_booktitle()}")

num_words = 10000
reading_time = Book.calculate_reading_time(num_words)
print(f"Estimated reading time: {reading_time:.2f} minutes")