# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I45K6RaGjirSOxYHVZdCJ8H09eID8LLS
"""

!mkdir math_package

!mkdir math_package/math

!touch math_package/math/__init__.py

!touch math_package/math/arithmetic.py

!touch math_package/main.py

#then in my main.py i used print statements and imported my functions from arithmetic.py

#i was having trouble here, my code wasnt importing add into main.py
from math_package.math.arithmetic import add, subtract, multiply, divide, modulus

def main():
    # Basic arithmetic operations
    print("Basic Arithmetic Operations:")
    print("Addition:", add(5, 3))
    print("Subtraction:", subtract(5, 3))
    print("Multiplication:", multiply(5, 3))
    try:
        print("Division:", divide(5, 3))
    except ValueError as e:
        print(e)
    print("Modulus:", modulus(5, 3))

if __name__ == "__main__":
    main()